graph TD
  A["서블릿 Filter 인터페이스"]
  B["GenericFilterBean<br>추상클래스"]
  C["OncePerRequestFilter"]

  subgraph "필터 구현들"
    D1["구현1"]
    D2["구현2<br>(필터로 등록)"]
    D3["구현3<br>(필터로 등록)"]
    D4["구현4<br>(필터로 등록)"]
    E1["구현5"]
    E2["구현6<br>(필터로 등록)"]
    E3["구현7<br>(필터로 등록)"]
    E4["구현8<br>(필터로 등록)"]
  end

  A --> B
  B --> C
  C --> D1
  D1 --> D2
  C --> E1
  E1 --> E2
  C --> D4
  C --> E3
  B --> D3
  B --> E4
